version: '3'

services:
  app:
    build: .
    ports:
      - 3001:3001 #Porta da máquina / Porta do container
      - 5555:5555 # Porta para o prisma Studio - O extensão do VsCode Dev Container faz isso automaticamente
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
  db:
    image: bitnami/mongodb:5.0.17
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_ROOT_PASSWORD: root
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: 123456
      MONGODB_DATABASE: nest

volumes:
  mongodb_data:
    driver: local